name: Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout module
        uses: actions/checkout@v2
      - name: Set Deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.4.4
      - name: Linting
        run: deno lint --unstable
      - name: Test Deno Module
        run: deno test --allow-net
