name: Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout module
        uses: actions/checkout@v2
      - name: Set Deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.4.4
      - name: Install task runer
        run: deno install -qA -n vr https://deno.land/x/velociraptor@1.0.0-beta.14/cli.ts
      - name: Linting
        run: vr lint
      - name: Test Deno Module
        run: vr test
